### ISSUE TITLE
Добавить команду для создания ивентов

### ISSUE THREAD

**Issue by kruall** [Ferlern/CindocuBot#15]
Пользователь задает разметку ембеда, и время его отправки. После чего бот в указанное время пишет  о ивенте в указанное время

Так же должна быть команда списка запланированных ивентов

Надо предусмотреть отмену ивента, возможно тоже с ембедом, если анонс уже был
Возможно еще надо для одного ивента иметь несколько зашедуленных сообщений: анонс, напоминалка заранее, начало ивента, завершение ивента

Разметка ембеда требует уточнения.
Возможно будут захардкоженные типы ивентов с полями для вставки доп инфы

**Comment by Ferlern** [comment]
Пользователь задает разметку ембеда и время начала ивента, эмбед отправляется сразу и помимо прочего содержит информацию о времени проведения.

Эмбед содержит:
 - название ивента
 - описание ивента
 - время проведения ивента
 - организатор
 - картинка (опционально)
 - награда (опционально)

Создание ивента должно включать:
- Выбор типа ивента (несколько стандартных (например из базы данных) с изначально определённым названием, описанием и картинкой или «другое», что подразумевает создание с нуля)
- Заполнение всех полей эмбеда
- Предпросмотр эмбеда перед его отправкой (как вариант, сразу отображать все изменения)
- Планирование упоминаний (к примеру, ивентер может выбрать упоминуть людей за 10 и 3 минуты до начала, либо не упоминать совсем)

**Comment by Ferlern** [comment]
Будем использовать ивенты от дискорда
