### ISSUE TITLE
Добавить донатную подписку

### ISSUE THREAD

**Issue by kruall** [Ferlern/CindocuBot#3]
Донат можно будет кидать по старому, как всегда, но при этом также купить подписку. Подписка будет стоить 1500 рублей, давать 1000 монет, 100 начальной нитры и 25 нитры (донатная валюта) за каждый новый уровень и роль Цикку. Подписка выдается на месяц.

**Comment by Ferlern** [comment]
Мы отказались от идеи подписки. Возможно, в будущем будут какие-то аналоги, но с другим функционалом
